version: "3.8"

services:
  master:
    image: locustio/locust:latest
    platform: linux/amd64
    command: >
      -f /locust/load_test.py
      --master
      --expect-workers 3
    ports:
      - "8089:8089"
      - "5557:5557"
    volumes:
      - ../src:/locust:ro

  exporter:
    image: containersol/locust_exporter
    platform: linux/amd64
    environment:
      - LOCUST_EXPORTER_LOCUST_HOST=http://master:8089
      - LOCUST_EXPORTER_WEB_LISTEN_ADDRESS=:9646
    ports:
      - "9646:9646"
